{
 "title": "Main portfolio dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Basic portfolio info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total portfolio price",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({type=\"ticker_current\"} * on(ticker) {type=\"ticker_quantity\"})"
    }
   ]
  },
  {
   "title": "Portfolio inner",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{type=\"ticker_current\"} * on(ticker) {type=\"ticker_quantity\"}",
     "legendFormat": "{{ticker}}"
    }
   ]
  },
  {
   "title": "Income by ticker",
   "type": "stat",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "({type=\"ticker_current\"} - on(ticker) {type=\"ticker_average\"}) * on(ticker) {type=\"ticker_quantity\"}",
     "legendFormat": "{{ticker}}"
    }
   ]
  },
  {
   "title": "Portfolio income",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({type=\"ticker_current\"} * on(ticker) {type=\"ticker_quantity\"}) / sum({type=\"ticker_average\"} * on(ticker) {type=\"ticker_quantity\"}) - 1"
    }
   ]
  },
  {
   "title": "Total income",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({type=\"ticker_current\"} * on(ticker) {type=\"ticker_quantity\"}) - sum({type=\"ticker_average\"} * on(ticker) {type=\"ticker_quantity\"})"
    }
   ]
  }
 ]
}